import type { Metadata } from "next"
import "@/app/globals.css"
import Header from "@/components/common/Header/Header"
import Footer from "@/components/common/Footer"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<Header />
			<main className="flex min-h-svh flex-col relative pt-24">
				{children}
			</main>
            <Footer />
		</>
	)
}
