import type { Metadata } from "next"
import "@/app/globals.css"
import { BackButton } from "@/app/(authentication)/_component/BackButton"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<main className="flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10 relative">
			<BackButton />
			<div className="w-full max-w-sm">{children}</div>
		</main>
	)
}
