export const config = {
    TITLE: "Abodex",
    TRUSTED_ORIGINS: process.env.TRUSTED_ORIGINS ? process.env.TRUSTED_ORIGINS?.split(",") : ["http://localhost:3000", "http://127.0.0.1:3000"],
    NODE_ENV: process.env.NODE_ENV ?? "development",
    BASE_URL: process.env.BETTER_AUTH_BASE_URL ?? "http://localhost:3000",
    DOMAIN: process.env.DOMAIN ?? "localhost:3000",
    FROM_EMAIL: process.env.FROM_EMAIL ?? "Abodex LTD <jeremiahedavid@gmail.com>",
    DATABASE_URL: process.env.DATABASE_URL,
    REDIS_URL: process.env.REDIS_URL ?? "",
    ADDRESS: process.env.ADDRESS ?? "123 Financial District, Suite 100",
    CITY: process.env.CITY ?? "San Francisco",
    STATE: process.env.STATE ?? "Texas",
    ZIP_CODE: process.env.ZIP_CODE ?? "20101",
    EMAIL_COMPLAINTS: process.env.SUPPORT_EMAIL ?? "complaints@abodex.com.ng",
    PHONE_NUMBER: process.env.PHONE_NUMBER ?? "+1 (234) 384 7729",
    GMAIL_USER: process.env.NODE_MAILER_GMAIL_APP_USERNAME,
    GMAIL_PASS: process.env.NODE_MAILER_GMAIL_APP_PASSWORD,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SK: process.env.GOOGLE_CLIENT_SK,
    LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID,
    LINKEDIN_CLIENT_SK: process.env.LINKEDIN_CLIENT_SK,
    CLOUDINARY_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_NAME,
    CLOUDINARY_API: process.env.NEXT_PUBLIC_CLOUDINARY_API,
    CLOUDINARY_SECRET: process.env.CLOUDINARY_SECRET,
    ARCJET_API_KEY: process.env.ARCJET_API_KEY,
}